### ISSUE TITLE
What else need to do after import?

### ISSUE THREAD

**Issue by robert1112** [zjuul/gtm4wp_container#1]
Hi 

BIG THANKS for your sharing. That saves more than 1 hr. You are so generous.

I just import and change UA-11111111-1 to mine in GA config - with ecommerce. What else do you recommend to do? 

If I have facebook pixel, I think the plugin or data layer won't help right? Thank you so much.

**Comment by zjuul** [comment]
You're welcome! Glad you like it.

Regarding the facebook pixels: make tags that contain these pixels, and let them trigger on one or more of the triggers that you have now.

E-commerce, form submits, content-bottom.. you choose.

**Comment by robert1112** [comment]
@zjuul Of course, you save my life. 😄  

Regarding FB pixel, do you happen having the json file to share? 

I installed FB base pixel but I have problem configuring values like total amount etc in FB backend. Are these values like purchase amount and product name etc can be fetched from GTM4WP?  How can that be done? Can you kindly advice? Thank you so much.

**Comment by zjuul** [comment]
These values can be extracted from the dataLayer. Here's a howto: http://marketlytics.com/blog/pull-ecommerce-data-from-datalayer-gtm

**Comment by robert1112** [comment]
@zjuul  You save my life TWICE! 🥇 I will have a look. Thank you.
