### ISSUE TITLE
Same web property ID is tracked twice

### ISSUE THREAD

**Issue by robert1112** [zjuul/gtm4wp_container#2]
Hi @zjuul  

I ran into this warning. Should I ignore it? I import to a blank GTM tag list and only change tracking to mine. Can you kindly advice? Thank you so much. 
<img width="442" alt="screen shot 2018-08-23 at 9 33 33 pm" src="https://user-images.githubusercontent.com/23134805/44528661-b147dd80-a71c-11e8-9731-f8566466e627.png">

**Comment by zjuul** [comment]
Do not ignore it. Research further: is there a page view tag fired twice by GTM?
Or is there already a pageview hardcoded on the page?
What does the GTM preview say?

**Comment by robert1112** [comment]
Here is the screenshot. 
<img width="1277" alt="screen shot 2018-08-23 at 10 52 16 pm" src="https://user-images.githubusercontent.com/23134805/44533362-f6254180-a727-11e8-9f4e-f96849f60f22.png">

Tracking ID in GA config - with ecommerce is my UA ID, not GTM ID, right?

Do you think I should remove the GTM4WP folder and start over again to check? Thanks.

**Comment by robert1112** [comment]
I noticed 「UA Enhanced Ecommerce WOO」are not fired on cart and checkout page. Is it correct?

**Comment by zjuul** [comment]
If a datalayer event is pushed and there is no trigger that is fired, it's probably a bug in the container.

If no datalayer event is pushed, it's probably intended behavior. Or there's a bug in your theme or gtm4wp config.

You can always fire a checkout event by creating your own trigger based on url.

**Comment by zjuul** [comment]
If you think you found a mistake in the container, describe what's missing or what's wrong, and I'll release a fix.

**Comment by robert1112** [comment]
I will check those points and update if any finding. Thank you so much.
