### ISSUE TITLE
UA Enhanced Ecommerce WOO fires twice.

### ISSUE THREAD

**Issue by robert1112** [zjuul/gtm4wp_container#3]
Hi @zjuul 

I got a minor problem here. UA Enhanced Ecommerce WOO got fired twice when add a product to cart. Below is from debug mode. 

```
Messages Where This Tag Fired
11 gtm4wp.addProductToCart 
12 gtm4wp.addProductToCartEEC
```
How can remove `gtm4wp.addProductToCartEEC` thanks.

**Comment by robert1112** [comment]
I tried and very luckily solve it by changing to`gtm4wp.addProductToCart$|gtm4wp.productClick$|gtm4wp.removeFromCart$|gtm4wp.checkoutOption$`

Thanks.

**Comment by zjuul** [comment]
<img width="318" alt="settings" src="https://user-images.githubusercontent.com/10512183/44569800-d7509a80-a77b-11e8-8cd5-cb75c838d8b2.png">

In WP, check one of the two, not both.
